window.onload = function(){
	//表头
	$("#dh1").mouseover(function(){
		$(this).find("#ol1")
			   .css({"display":"block","background":"#fff"})
	})
	$("#dh1").mouseleave(function(){
		$(this).find("#ol1")
			   .css("display","none")
	})
	$("#wx").mouseover(function(){
		$(this).find("#wximg")
		.css({
			"display":"block","background":"#fff"
		})
	})
	$("#wx").mouseleave(function(){
		$(this).find("#wximg")
		.css("display","none")
	})
	$("#ewm").mouseover(function(){
		$(this).find("#ewmimg")
			   .css({"display":"block","background":"#fff"})
	})
	$("#ewm").mouseleave(function(){
		$(this).find("#ewmimg")
				.css("display","none")
	})			
	$("#mj").mouseover(function(){
		$(this).find("#mjzx")
				.css({"display":"block","background":"#fff"})
	})
	$("#mj").mouseleave(function(){
		$(this).find("#mjzx")
		       .css("display","none")
	})	
	$("#wzdh").mouseover(function(){
		$(this).find("#dh")
		        .css("display","block")
	})
	$("#wzdh").mouseleave(function(){
		$(this).find("#dh")
			.css("display","none")
	})
	$(".tb").mouseover(function(){
		$(this).css("")
	})
	//搜索框
	$(".searchcont").mouseover(function(){
		$(this).find("#spdp").css("display","block")
	})
	$(".searchcont").mouseleave(function(){
		$(this).find("#spdp").css("display","none")
	})
}
